use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    emit_embedded(
        &manifest_dir,
        &out_dir,
        "profiles",
        "profiles_embedded.rs",
        "BUILTIN_PROFILES",
        "Built-in profile layers embedded at compile time, as `(name, toml_body)` pairs walked from `profiles/**/*.toml`.",
    );
    emit_embedded(
        &manifest_dir,
        &out_dir,
        "recipes",
        "recipes_embedded.rs",
        "BUILTIN_RECIPES",
        "Built-in recipes embedded at compile time, as `(id, toml_body)` pairs walked from `recipes/**/*.toml`.",
    );
}

fn emit_embedded(
    manifest_dir: &Path,
    out_dir: &Path,
    tree: &str,
    out_name: &str,
    const_name: &str,
    doc: &str,
) {
    let dir = manifest_dir.join(tree);
    println!("cargo:rerun-if-changed={tree}");

    let mut entries: Vec<(String, String)> = Vec::new();
    collect_toml(&dir, &dir, tree, &mut entries);
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = format!(
        "// Generated by build.rs — do not edit.\n\
         /// {doc}\n\
         pub const {const_name}: &[(&str, &str)] = &[\n"
    );
    for (name, rel) in &entries {
        let rel_unix = rel.replace('\\', "/");
        code.push_str(&format!(
            "    (\"{name}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{rel_unix}\"))),\n"
        ));
    }
    code.push_str("];\n");

    fs::write(out_dir.join(out_name), code).unwrap_or_else(|e| {
        panic!("write {out_name}: {e}");
    });
}

fn collect_toml(base: &Path, dir: &Path, tree: &str, out: &mut Vec<(String, String)>) {
    let read_dir = match fs::read_dir(dir) {
        Ok(d) => d,
        Err(_) => return,
    };
    for entry in read_dir.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_toml(base, &path, tree, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("toml") {
            let rel = path.strip_prefix(base).unwrap();
            let name = rel.with_extension("").to_string_lossy().replace('\\', "/");
            let rel_manifest = Path::new(tree).join(rel);
            out.push((name, rel_manifest.to_string_lossy().into_owned()));
        }
    }
}
