use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let profiles_dir = manifest_dir.join("profiles");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("profiles_embedded.rs");

    println!("cargo:rerun-if-changed=profiles");

    let mut entries: Vec<(String, String)> = Vec::new();
    collect_toml(&profiles_dir, &profiles_dir, &mut entries);
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::from(
        "// Generated by build.rs — do not edit.\n\
         pub const BUILTIN_PROFILES: &[(&str, &str)] = &[\n",
    );
    for (name, rel) in &entries {
        let rel_unix = rel.replace('\\', "/");
        code.push_str(&format!(
            "    (\"{name}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{rel_unix}\"))),\n"
        ));
    }
    code.push_str("];\n");

    fs::write(out_file, code).expect("write profiles_embedded.rs");
}

fn collect_toml(base: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    let read_dir = match fs::read_dir(dir) {
        Ok(d) => d,
        Err(_) => return,
    };
    for entry in read_dir.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_toml(base, &path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("toml") {
            let rel = path.strip_prefix(base).unwrap();
            let name = rel.with_extension("").to_string_lossy().replace('\\', "/");
            let rel_manifest = Path::new("profiles").join(rel);
            out.push((name, rel_manifest.to_string_lossy().into_owned()));
        }
    }
}
