# toolchains/apple-toolchain-core
# Toolchain: Apple Toolchain Core Curated Apple Command Line Tools binaries and support data that many macOS
# filter = { os = ["macos"] }  # macOS-only layer (filter not parsed yet)

requires = ["macos/system-runtime"]

paths = [
  { path = "/Library", access = "ro", match = "literal" },
  { path = "/Library/Developer", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/include", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/lib", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/libexec", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/libexec/git-core", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/share", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/SDKs", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/git", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/make", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/gnumake", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/c++", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/cc", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/clang", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/gcc", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/g++", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/cpp", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/c89", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/c99", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/ar", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/ranlib", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/as", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/ld", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/ld-classic", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/libtool", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/lipo", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/codesign_allocate", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/dsymutil", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/bitcode_strip", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/install_name_tool", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/strip", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/bison", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/byacc", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/flex", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/flex++", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/lex", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/yacc", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/m4", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/gm4", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/bm4", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/gperf", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/ctags", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/mig", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/rpcgen", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/libexec/migcom", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/unifdef", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/unifdefall", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/clang-format", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/clangd", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/c++filt", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/gcov", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/lorder", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/nm", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/objdump", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/otool", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/size", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/strings", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/llvm-cov", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/llvm-cxxfilt", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/llvm-dwarfdump", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/llvm-nm", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/llvm-objdump", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/llvm-otool", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/llvm-profdata", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/llvm-size", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/dyld_info", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/cmpdylib", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/nm-classic", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/otool-classic", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/pagestuff", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/size-classic", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/nmedit", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/segedit", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/bin/vtool", access = "ro", match = "literal" },
  { path = "/Library/Developer/CommandLineTools/usr/libexec/git-core", access = "ro" },
  { path = "/Library/Developer/CommandLineTools/usr/include", access = "ro" },
  { path = "/Library/Developer/CommandLineTools/usr/lib", access = "ro" },
  { path = "/Library/Developer/CommandLineTools/usr/share", access = "ro" },
  { path = "/Library/Developer/CommandLineTools/SDKs", access = "ro" },
]
